import type { Habit } from './habit';
import type { Reward } from './reward';

export const INITIAL_HABITS: Habit[] = [
  {
    id: '1',
    emoji: '🏋️',
    name: 'Ejercicio 30 min',
    pointsPerDay: 5,
    penalty: 2,
    streak: 2,
    completionStatus: [
      'completed',
      'completed',
      'pending',
      'pending',
      'pending',
      'pending',
      'pending',
    ],
  },
  {
    id: '2',
    emoji: '📚',
    name: 'Leer 20 páginas',
    pointsPerDay: 3,
    penalty: 1,
    streak: 0,
    completionStatus: [
      'completed',
      'failed',
      'pending',
      'pending',
      'pending',
      'pending',
      'pending',
    ],
  },
  {
    id: '3',
    emoji: '😴',
    name: 'Dormir 8 horas',
    pointsPerDay: 4,
    penalty: 2,
    streak: 0,
    completionStatus: [
      'completed',
      'pending',
      'pending',
      'pending',
      'pending',
      'pending',
      'pending',
    ],
  },
  {
    id: '4',
    emoji: '🚫',
    name: 'Sin redes sociales',
    pointsPerDay: 3,
    penalty: 1,
    streak: 0,
    completionStatus: [
      'completed',
      'pending',
      'pending',
      'pending',
      'pending',
      'pending',
      'pending',
    ],
  },
  {
    id: '5',
    emoji: '🐶',
    name: 'Pasear la mascota',
    pointsPerDay: 2,
    penalty: 1,
    streak: 0,
    completionStatus: [
      'completed',
      'pending',
      'pending',
      'pending',
      'pending',
      'pending',
      'pending',
    ],
  },
];

export const INITIAL_REWARDS: Reward[] = [
  {
    id: '1',
    emoji: '📺',
    name: 'Película favorita',
    description: 'Disfruta de una película sin culpa',
    cost: 39,
  },
  {
    id: '2',
    emoji: '🍕',
    name: 'Comida especial',
    description: 'Pide tu comida favorita',
    cost: 69,
  },
  {
    id: '3',
    emoji: '🏖️',
    name: 'Día libre',
    description: 'Un día completo de descanso',
    cost: 139,
  },
  {
    id: '4',
    emoji: '🎁',
    name: 'Capricho personal',
    description: 'Compra algo que desees',
    cost: 189,
  },
];
